.TH "Simple Shell" "1" "27 August 2018" "Simple Shell man page" "Simple Shell man page"
.SH NAME
.B hsh
- A simple shell.
.SH SYNOPSIS
.B ./hsh
- built according to Holberton School project guidlines. Meant to closely emulate the Thompson shell.
.SH DESCRIPTION
.B hsh
replicates the functionality of the Thompson Shell. It is a command language interpreter that reads commands either from the standard input, or piped in. It then interprets and executes them.
.SH INVOCATION
.B hsh
can be invoked in one of two ways: In interactive mode by running
.B ./hsh
and typing commands from the keyboard, or in non-interactive mode by piping commands into the program using echo or cat.
.SH BUILT-IN COMMANDS
.B exit
- exits the shell
.B env
- prints the environment
.SH OPTIONS
.B hsh
does not currently take any options.
.SH RETURN VALUE
The program will return 0 on success and another number upon an error or failure.
.SH EXAMPLE
.B In interactive mode:

$ ./hsh
.P
($) /bin/ls
.P
hsh main.c shell.c
.P
($)
.P
($) exit
.P
$
.P
.P
.B In non-interactive mode:

$ echo "/bin/ls" | ./hsh
.P
hsh main.c shell.c test_ls_2
.P
$
.SH SEE ALSO
.I sh(1), bash(1)
.SH BUGS
Known bugs when using the PATH in unusual ways. Under review.
.SH AUTHOR
Essence Boayue, Erwin Gove
